Repository CS2103-AY1819S2-W16-4/main, pull requests merged in 2019-04, with the labels that each got.

#68 Update of Documents
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/barisbatuhan.adoc
Labels: priority.High, type.Task

#70 [V1.3] Failing Test cases are fixed, Filtering Tests are added
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task, type.Test

#73 [v1.3] tests are rearranged
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/seedu/address/ui/PersonCardTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/ResultDisplayTest.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.High, type.Task, type.Test

#81 v1.3
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Task

#97 Implementation of three new sort commands
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortEducation.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortGpa.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortName.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortSkills.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortSurname.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortTagNumber.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortUtil.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonUtil.java
Labels: priority.Medium, type.Enhancement

#98 CheckStyle Errors for Main are fixed
  src/main/java/seedu/address/logic/commands/sortmethods/SortEducation.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortGpa.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortName.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortSkills.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortSurname.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortTagNumber.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortUtil.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/PersonUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
Labels: priority.High, type.Task

#99 StyleCheck error fixes v2 and Filtering input style is changed
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: priority.High, type.Task

#100 [v1.4] Enhancements for filtering
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
Labels: priority.Low, type.Enhancement

#101 Filter Command Updates
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Gpa.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: priority.Medium, type.Enhancement

#102 [v1.4] CheckStyle Main errors fixed
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
Labels: priority.High, type.Task

#103 [v1.4] styleCheck Errors are fixed for testing
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/seedu/address/ui/PersonCardTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/ResultDisplayTest.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.High, type.Task, type.Test

#104 [v1.4] checkStyle for Tests are updated again
  src/test/java/seedu/address/logic/commands/FilterCommandIntegrationTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Task, type.Test

#105 [v1.4] checkStyle updates for testing v3
  src/test/java/seedu/address/logic/commands/FilterCommandIntegrationTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: priority.High, type.Task, type.Test

#106 UserGuide and Portfolio Updates
  docs/UserGuide.adoc
  docs/images/UI.png
  docs/team/barisbatuhan.adoc
Labels: priority.High, type.Task

#107 [v1.4] Unit tests for FilterCommand and FilterCommandParser are updated
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: priority.Medium, type.Story, type.Test

#110 mid v1.4
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortEducation.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortGpa.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortName.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortSkills.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortSurname.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortTagNumber.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonCardTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.High

#112 Test Updates
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.High, type.Bug, type.Test

#113 [v1.4] All failing tests are fixed except systemtests
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.Medium, type.Task, type.Test

#114 checkStyleFixes
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.High, type.Bug

#115 For filtering, new tests are added, old tests are rewritten
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/resources/images/address_book_32.png
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
Labels: priority.Medium, type.Task, type.Test

#116 Systemtest changes
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.High, type.Task, type.Test

#119 Filter Command Integration and Unit Tests
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/commands/FilterCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
Labels: priority.Medium, status.Ongoing, type.Story, type.Test

#121 CV showing is implemented, Changes in filtering and test cases
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/html/bensonmeier.html
  src/main/resources/view/html/brucewayne.html
  src/main/resources/view/html/cv/bruce-wayne.jpg
  src/main/resources/view/html/cv/peter-parker.jpg
  src/main/resources/view/html/cv/placeholder.jpg
  src/main/resources/view/html/cv/tony-stark.jpg
  src/main/resources/view/html/peterparker.html
  src/main/resources/view/html/placeholder.html
  src/main/resources/view/html/tonystark.html
  src/test/java/seedu/address/logic/commands/FilterCommandIntegrationTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: priority.Medium, type.Story, type.Test

#123 Coveralls and Codacy Implementation
  .coveralls.yml
  .travis.yml
  README.adoc
Labels: priority.Low, type.Task

#124 UI image is updated
  README.adoc
  docs/images/UI.png
  docs/images/Ui.png
Labels: priority.High, type.Task

#127 README file informations are updated
  README.adoc
Labels: priority.High, type.Task

#129 UserGuide is updated
  README.adoc
  docs/UserGuide.adoc
Labels: priority.High, status.Ongoing, type.Task

#133 Failing tests are fixed, UI image is updated
  docs/images/Ui.png
  docs/team/barisbatuhan.adoc
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/guitests/guihandles/PersonListPanelHandle.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EndorseCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandIntegrationTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.Medium, type.Bug, type.Task, type.Test

#134 checkStyleErrors
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EndorseCommand.java
  src/main/java/seedu/address/logic/commands/sortmethods/SortSkills.java
  src/main/java/seedu/address/model/person/Degree.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.High, type.Bug, type.Task

#135 checkStyle Fixes
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High, type.Bug, type.Task

#136 checkStyle
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High, type.Bug, type.Task

#138 checkStyle Main fix
  src/main/java/seedu/address/model/person/Gpa.java
  src/test/java/guitests/guihandles/PersonListPanelHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: priority.High, type.Bug

#139 Degree filtering is added, test cases are arranged according to that
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: priority.Medium, type.Enhancement

#140 System tests are fixed
  src/main/java/seedu/address/model/tag/SkillsTag.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.Medium, type.Bug, type.Task, type.Test

#141 Documentation Updates
  README.adoc
  docs/UserGuide.adoc
Labels: type.Task

#143 Developer Guide and Portfolio is finalized.
  docs/DeveloperGuide.adoc
  docs/images/class-diagram-filter.png
  docs/images/filterDiagram.png
  docs/images/sequence-diagram-filter.png
  docs/team/barisbatuhan.adoc
Labels: priority.High, type.Task

#149 no message
  docs/DeveloperGuide.adoc
  docs/team/barisbatuhan.adoc
Labels: priority.High, type.Enhancement

#150 UserGuide and barisbatuhan Portfolio is updated
  docs/UserGuide.adoc
  docs/team/barisbatuhan.adoc
Labels: priority.High, type.Enhancement

#151 Document Updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/barisbatuhan.adoc
Labels: priority.High, type.Enhancement

#152 Developer Guide Update
  docs/DeveloperGuide.adoc
  docs/team/barisbatuhan.adoc
Labels: priority.High, type.Enhancement

#153 Developer Guide Tag Update
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Bug

#154 Developer Guide Update
  docs/DeveloperGuide.adoc
  docs/team/barisbatuhan.adoc
Labels: priority.High, type.Bug

#155 Developer Guide Update
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Enhancement

#156 Sample Data at Beginning is Improved
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Low, type.Enhancement

#159 Developer Guide Fix
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Bug

#162 Tag in a wrong place problem fix in Developer Guide
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Bug
